# Abstract

```{r}
#| label: setup
#| include: false

source(here::here("R/_setup.R"))
```

Climate change has the potential to affect the availability, access, and utilization of food, as well as the stability of food systems. This synergistic impact between climate change, malnutrition, and obesity is recognized as a Global Syndemic, resulting in significant challenges for populations around the world. In Brazil, we observe evidence of this challenge, with more than 60% of the population being overweight and over 10 million people facing severe food insecurity [@ibge2020]. Additionally, about 7% of Brazilian children under five years old have low height for their age, and 5% are overweight for their age [@ufrj2022], indicators considered suboptimal by the World Health Organization [@whoa]. Future projections are even more alarming, predicting that by 2035, half of Brazilian children could be considered obese [@wof2024]. Nonetheless, there is a significant knowledge gap regarding the relationship between anthropometric indicators and environmental factors, such as climate change and extreme weather events. This work aims to address this gap by proposing to: 1 - Conduct a literature review on the metrics used to measure climate change; 2 - Analyze the operation of the Global Syndemic of malnutrition, obesity, and climate change based on the literature; 3 - Investigate the relationship between the intensification of extreme weather events and the occurrence of malnutrition and obesity in children under five years old in Brazil.
