# Objectives

```{r}
#| label: setup
#| include: false

source(here::here("R/quarto-setup.R"))
```

## General Objective

Evaluate the impact of anthropogenic climate change on obesity and malnutrition patterns in Brazilian children under five years old, considering the context of the global syndemic.

## Specific Objectives

1. Conduct a comprehensive review of the metrics used to measure anthropogenic climate change and extreme weather events.
2. Analyze the scope of the global syndemic, understanding the interrelationships between obesity, malnutrition, and climate change, based on the literature review.
3. Develop and manage a comprehensive database containing variables related to climate, food systems, and child health, focusing on those monitored by the Brazilian Unified Health System (SUS) within the framework of Primary Health Care.
4. Investigate the relationship between the increased frequency of extreme events and obesity and malnutrition in children under five years old using network-based analyses.
