# Methods

```{r}
#| label: setup
#| include: false

source(here::here("R/quarto-setup.R"))
```

## Literature review

For the literature review, we adopt the PICO methodology [@koricheva2013], considering:

* \(P\) Population: children < 5 years old monitored by the SUS.
* \(IC\) Intervention/Context: climate change affecting children's food health
* \(O\) Outcome: Increase in obesity and malnutrition.

The search key includes terms related to climate change, children, and nutritional outcomes. The databases [Scopus](https://www.scopus.com), MEDLINE ([PubMed](https://pubmed.ncbi.nlm.nih.gov/)), and Web of Science ([WoS](https://www.webofscience.com/wos/)) were chosen for the search.

## Databases

Public health and climate databases from municipalities, accessible on public websites, will be used, including:

* Information on the nutritional status of children under five years old, from the Food and Nutrition Surveillance System ([SISVAN](https://sisaps.saude.gov.br/sisvan/)) based on Brazilian Unified Health System (SUS) services between 2008 and 2022.
* Data on food consumption of children under five years old, from the Food and Nutrition Surveillance System ([SISVAN](https://sisaps.saude.gov.br/sisvan/)) based on SUS services between 2015 and 2022.
* Records of greenhouse gas emissions at the municipal level, from the Greenhouse Gas Emission Estimation System ([SEEG Brazil](https://seeg.eco.br/)) (2000-2019).
* Information on anthropogenic changes in municipalities, such as land use changes, from [MapBiomas Brasil](https://brasil.mapbiomas.org/) between 2000 and 2019, and other sources.
* Additionally, databases containing essential information about municipalities, such as population size, population density, number of children under five years old, Human Development Index (HDI), and adherence to the Family Health Program, obtained through the [MUNIC](https://www.ibge.gov.br/estatisticas/sociais/educacao/10586-pesquisa-de-informacoes-basicas-municipais.html), [Cidades](https://cidades.ibge.gov.br/), and [2022 Census](https://censo2022.ibge.gov.br/) sources of the [IBGE](https://www.ibge.gov.br/).

## Variables of interest

To assess the global syndemic, we consider: 

* Health variables: BMI, height and food consumption.
* Environmental variables: gas emissions and variables derived from temperature and precipitation.
* Socioeconomic variables: population, density and HDI.

Children will be classified according to nutritional status, and the variables will be normalized to the number of children in the municipality.

## Complex systems methodology

Complex systems techniques, including network analysis and agent-based modeling (ABM), will be employed. A conceptual model will be built from the literature review, representing municipalities and children as agents. The environment will be defined by the climatic conditions of each municipality. Mathematical models will be used to represent interactions and system dynamics. The implementation will be carried out in Python, R, or Netlogo, and the results will be summarized in a management platform (Shiny).
