# INMET data

```{r}
#| label: setup
#| include: false

source(here::here("R/_setup.R"))
```

```{r}
#| echo: false
#| output: asis

rutils:::quarto_status(
  type = "drafting",
  of_what = "of this report"
  )
```

```{r}
#| eval: false
#| code-fold: false

library(BrazilMet)
library(rvest)
library(string)
library(utils)
```

## Web scraping

```{r}
#| eval: false
#| code-fold: false
html <- rvest::read_html("https://portal.inmet.gov.br/dadoshistoricos")

data_links <- html |>
  rvest::html_elements("a") |>
  rvest::html_attr("href") |>
  stringr::str_subset("^http+[s]?:/") |>
  stringr::str_subset("dadoshistoricos")
```

## Dowloading and unzipping the data

```{r}
#| eval: false
#| code-fold: false

year <- "2024"

dir_path <- here::here(".data", "inmet", "dados-historicos", year, "zip")

if (!dir.exists(dir_path)) {
  dir.create(dir_path, recursive = TRUE, showWarnings = FALSE)
}

dest_file <- 
  dir_path |>
  here::here(paste0("inmet_dados-historicos_", year, ".zip"))

url <- data_links |> 
  stringr::str_subset(year) %>% 
  `[`(1)

curl::curl_download(url = url, destfile = dest_file)

dir_path <- dir_path |> stringr::str_replace("zip$", "csv")

if (!dir.exists(dir_path)) {
  dir.create(dir_path, recursive = TRUE, showWarnings = FALSE)
}

files <- utils::unzip(zipfile = dest_file, exdir = dir_path)
```

## Reading data

```{r}
#| eval: false
#| code-fold: false

tidy_inmet_values <- function(x) {
  checkmate::assert_character(x, min.len = 1)
  
  x |>
  stringr::str_to_upper() |>
  iconv(from = 'UTF-8', to = 'ASCII//TRANSLIT')
}

```

```{r}
#| eval: false
#| code-fold: false

# files <-
#   here::here(".data", "inmet", "dados-historicos", year, "csv") |>
#   list.files(full.names = TRUE)

city <- "São Paulo" |> tidy_inmet_values()
station <- "Interlagos" |> tidy_inmet_values()

file <-
  files |>
  stringr::str_subset(city) |>
  stringr::str_subset(station)

data <- 
  file |>
  readr::read_delim(
    delim = ";",
    quote = "\"",
    escape_backslash = FALSE,
    escape_double = TRUE,
    col_names = TRUE,
    col_types = readr::cols(.default = "c"),
    col_select = NULL,
    id = NULL,
    locale = readr::locale(
      date_names = "pt",
      date_format = "%d/%m/%Y",
      time_format = "%H:%M:%S",
      decimal_mark = ",",
      grouping_mark = ".",
      tz = "America/Sao_Paulo",
      encoding = readr::guess_encoding(file)$encoding[1],
      asciify = FALSE
    ),
    na = c("", "NA"),
    comment = "",
    trim_ws = FALSE,
    skip = 8,
    n_max = Inf,
    guess_max = min(1000, Inf),
    name_repair = "unique",
    num_threads = readr::readr_threads(),
    progress = TRUE,
    show_col_types = FALSE,
    skip_empty_rows = TRUE,
    lazy = FALSE
  )

data |> dplyr::glimpse()
```

