project:
  type: book
  output-dir: _web
  pre-render: "R/_pre-render-html.R"
  post-render: "R/_post-render-html.R"

book:
  date: today
  date-format: "YYYY-MM-DD"
  repo-actions: [edit, issue]
  chapters:
    - index.qmd
    - qmd/abstract.qmd
    - qmd/objectives.qmd
    - qmd/methods.qmd
    - qmd/activities.qmd
    - part: "Data analyses"
      chapters:
        - qmd/report-1.qmd
        - qmd/report-2.qmd
        - qmd/report-3.qmd
        - qmd/report-4.qmd
        - qmd/report-5.qmd
    - part: "Paper"
      chapters:
        - qmd/manuscript.qmd
        - qmd/supp-materials.qmd
    - qmd/discussion.qmd
    - qmd/acknowledgments.qmd
    - qmd/references.qmd
    - qmd/glossary.qmd
  appendices:
    - qmd/appendix-report-1.qmd
    - qmd/appendix-report-2.qmd
    - qmd/appendix-report-3.qmd
    - qmd/example-of-use.qmd

format:
  html:
    date-format: "YYYY-MM-DD"
    open-graph: true
    locale: en
    number-depth: 5
    code-link: true
    code-fold: show
    cap-location: top
    reader-mode: false
    callout-appearance: simple
    csl: csl/english-apa-author-date.csl
    theme: [cosmo, scss/web-theme-light.scss]
